import React from 'react';
import ReactDOM from 'react-dom';

// create a new component
// product some html that will later be placed in the body
const App = () => {
  return <div>HI!</div>;
}


// take the html generated by the component and place in page
ReactDOM.render(<App />, document.querySelector('.container'));